workflows:
  web-release:
    name: Web Release
    environment:
      flutter: stable
    scripts:
      - script: flutter clean && flutter pub get
      - script: flutter build web --release --web-renderer canvaskit
    artifacts:
      - build/web/**
